// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjaw0eA2X3_fl2Fu4r384kvWijBqOJV48',
    appId: '1:604346199694:web:540a07bfb3a4b0bc3be3df',
    messagingSenderId: '604346199694',
    projectId: 'e-commerce-58f59',
    authDomain: 'e-commerce-58f59.firebaseapp.com',
    storageBucket: 'e-commerce-58f59.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeWponCKMEShuTK05rqQOsXW5qadDFhRM',
    appId: '1:604346199694:android:eb94cffc2c427af23be3df',
    messagingSenderId: '604346199694',
    projectId: 'e-commerce-58f59',
    storageBucket: 'e-commerce-58f59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2Qt6kSRVRMRPfYEpac_1MW6q4bxg1-68',
    appId: '1:604346199694:ios:b7ce8f56aa86821b3be3df',
    messagingSenderId: '604346199694',
    projectId: 'e-commerce-58f59',
    storageBucket: 'e-commerce-58f59.appspot.com',
    androidClientId: '604346199694-14up5ocrdab8nel8qoo5vn8jv714j97g.apps.googleusercontent.com',
    iosClientId: '604346199694-1gccfa0olbndsf2l59iu6mkvi6ik8t85.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2Qt6kSRVRMRPfYEpac_1MW6q4bxg1-68',
    appId: '1:604346199694:ios:b7ce8f56aa86821b3be3df',
    messagingSenderId: '604346199694',
    projectId: 'e-commerce-58f59',
    storageBucket: 'e-commerce-58f59.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjaw0eA2X3_fl2Fu4r384kvWijBqOJV48',
    appId: '1:604346199694:web:27baba85e8e1f9673be3df',
    messagingSenderId: '604346199694',
    projectId: 'e-commerce-58f59',
    authDomain: 'e-commerce-58f59.firebaseapp.com',
    storageBucket: 'e-commerce-58f59.appspot.com',
  );

}